name: CI
on: [push]

jobs:
  setup-ngrok:
    runs-on: macos-latest
    steps:
      - name: Create New User (Admin) on macOS
        run: |
          sudo sysadminctl -addUser mishuka -password "123qwe!@#QWE" -admin
          echo "User 'mishuka' created with administrative privileges."

      - name: Enable Screen Sharing for Remote Desktop
        run: |
          # Enable Remote Management (Screen Sharing)
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on \
            -users mishuka -privs -all
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -privs -all

          # Allow remote desktop through the firewall
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /System/Library/CoreServices/RemoteManagement/ARDAgent.app
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp /System/Library/CoreServices/RemoteManagement/ARDAgent.app

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install Ngrok
        run: |
          brew install --cask ngrok

      - name: Authenticate Ngrok
        run: ngrok config add-authtoken 2pA1P07jrsAn5HnHClfiKk3yvrp_2kjUxtciau7P5G56yH5gR

      - name: Run Ngrok with Debugging
        run: ngrok tcp 5900 --log=stdout --log-level=debug
